# Generated by Django 4.2.7 on 2023-12-03 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breaking_full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('breaking_date', models.DateField(default=datetime.datetime(2023, 12, 3, 10, 53, 22, 228355, tzinfo=datetime.timezone.utc), verbose_name='Дата')),
                ('breaking_room', models.IntegerField(default=101, verbose_name='Кабинет')),
                ('breaking_category', models.CharField(choices=[('Сантехника', 'Сантехника'), ('Компьютер или перефирийное устройство', 'Компьютер или перефирийное устройство'), ('Мебель', 'Мебель'), ('Здание', 'Здание')], max_length=1000, verbose_name='Категория поломки')),
            ],
            options={
                'verbose_name': 'Поломка',
                'verbose_name_plural': 'Поломки',
            },
        ),
    ]
