# Generated by Django 4.2.7 on 2023-12-03 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 3, 10, 54, 41, 729215, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
