# Generated by Django 4.2.7 on 2023-12-03 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0002_alter_breaking_breaking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking',
            name='breaking_category',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 3, 10, 56, 38, 608474, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
