# Generated by Django 4.2.7 on 2023-12-03 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0003_alter_breaking_breaking_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breaking',
            name='breaking_description',
            field=models.TextField(default='Опишите проблему', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='breaking',
            name='breaking_category',
            field=models.CharField(choices=[('Сантехника', 'Сантехника'), ('Компьютер или перефирийное устройство', 'Компьютер или перефирийное устройство'), ('Мебель', 'Мебель'), ('Здание', 'Здание')], max_length=1000, verbose_name='Категория поломки'),
        ),
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 3, 10, 59, 53, 589333, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
