# Generated by Django 4.2.7 on 2023-12-03 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0004_breaking_breaking_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 3, 11, 3, 0, 528931, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
