# Generated by Django 4.2.7 on 2023-12-03 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0005_alter_breaking_breaking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 3, 11, 5, 19, 428938, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
