# Generated by Django 4.2.7 on 2023-12-06 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0006_alter_breaking_breaking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='breaking',
            name='breaking_status',
            field=models.CharField(choices=[('Не выполнено', 'Не выполнено'), ('Выполнено', 'Выполнено'), ('В процессе', 'В процессе')], default=('Не выполнено', 'Не выполнено'), max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='breaking',
            name='breaking_category',
            field=models.CharField(choices=[('Сантехника', 'Сантехника'), ('Компьютер или перефирийное устройство', 'Компьютер или перефирийное устройство'), ('Мебель', 'Мебель'), ('Здание', 'Здание')], max_length=100, verbose_name='Категория поломки'),
        ),
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 6, 8, 30, 6, 879903, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
