# Generated by Django 4.2.7 on 2023-12-12 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0007_breaking_breaking_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breaking',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 12, 10, 7, 1, 575832, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='breaking',
            name='breaking_status',
            field=models.CharField(choices=[('Не выполнено', 'Не выполнено'), ('Выполнено', 'Выполнено'), ('В процессе', 'В процессе')], default='Не выполнено', max_length=100, verbose_name='Статус'),
        ),
    ]
