# Generated by Django 4.2.7 on 2023-12-18 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0008_alter_breaking_options_alter_breaking_breaking_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100, verbose_name='Название')),
                ('material_volume', models.DecimalField(decimal_places=1, max_digits=1, verbose_name='Количество')),
            ],
        ),
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 18, 10, 11, 37, 932813, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
