# Generated by Django 4.2.7 on 2023-12-18 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0009_material_alter_breaking_breaking_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 18, 10, 13, 15, 941752, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
