# Generated by Django 4.2.7 on 2023-12-18 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0010_alter_material_options_alter_breaking_breaking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='breaking',
            name='breaking_number',
            field=models.CharField(default='1', max_length=100, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 18, 10, 20, 55, 730011, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
