# Generated by Django 4.2.7 on 2023-12-18 10:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0012_breaking_breaking_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 18, 10, 27, 16, 709651, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='breaking',
            name='breaking_material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DGKP.material'),
        ),
    ]
