# Generated by Django 4.2.7 on 2023-12-18 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0015_alter_breaking_breaking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 18, 10, 35, 27, 768509, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
