# Generated by Django 4.2.7 on 2023-12-18 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0016_alter_breaking_breaking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 18, 10, 48, 3, 730657, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_volume',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=3, verbose_name='Количество'),
        ),
    ]
