# Generated by Django 4.2.7 on 2023-12-20 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0020_alter_breaking_breaking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 20, 9, 43, 1, 816400, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
