# Generated by Django 4.2.7 on 2023-12-24 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0023_alter_breaking_breaking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='material_volume',
        ),
        migrations.AddField(
            model_name='breaking',
            name='breaking_material_volume',
            field=models.DecimalField(decimal_places=1, default=1.1, max_digits=3, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 24, 10, 18, 27, 105367, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
