# Generated by Django 4.2.7 on 2023-12-27 20:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0024_remove_material_material_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 27, 20, 36, 5, 960842, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='breaking',
            name='breaking_material',
            field=models.ForeignKey(default='Ничего', on_delete=django.db.models.deletion.CASCADE, to='DGKP.material', verbose_name='Материал'),
        ),
    ]
