# Generated by Django 4.2.7 on 2024-01-03 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0027_breaking_breaking_worker_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 3, 12, 42, 15, 193275, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.RemoveField(
            model_name='breaking',
            name='breaking_material',
        ),
        migrations.AddField(
            model_name='breaking',
            name='breaking_material',
            field=models.ManyToManyField(blank=True, to='DGKP.material', verbose_name='Материалы'),
        ),
    ]
