# Generated by Django 4.2.7 on 2024-01-03 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0029_alter_breaking_options_alter_breaking_breaking_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breaking',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='breakingmaterial',
            options={},
        ),
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 3, 12, 53, 48, 406962, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
