# Generated by Django 4.2.7 on 2024-01-03 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0030_alter_breaking_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 3, 12, 56, 44, 641006, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
