# Generated by Django 4.2.7 on 2024-01-04 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('DGKP', '0031_alter_breaking_breaking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 4, 11, 49, 19, 636709, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_fullname', models.CharField(max_length=200, verbose_name='ФИО')),
                ('staff_phone_number', models.CharField(max_length=13, verbose_name='Тел. номер')),
                ('staff_group', models.ManyToManyField(blank=True, to='auth.group', verbose_name='Группы')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
