# Generated by Django 4.2.7 on 2024-01-04 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0034_alter_breaking_breaking_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='staff_group',
            new_name='staff_category',
        ),
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 4, 11, 51, 13, 912565, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
