# Generated by Django 4.2.7 on 2024-01-04 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('DGKP', '0035_rename_staff_group_staff_staff_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 4, 11, 51, 45, 516339, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_category',
            field=models.ManyToManyField(blank=True, to='auth.group', verbose_name='Категории'),
        ),
    ]
