# Generated by Django 4.2.7 on 2024-01-04 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0046_alter_breaking_breaking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 4, 12, 26, 4, 979393, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='breaking',
            name='breaking_material_volume',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Количество'),
        ),
    ]
