# Generated by Django 4.2.7 on 2024-01-04 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0048_alter_breaking_breaking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 4, 12, 49, 4, 19108, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
