# Generated by Django 4.2.7 on 2024-01-05 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0051_alter_breaking_breaking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 5, 8, 56, 21, 364750, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
