# Generated by Django 4.2.7 on 2024-01-07 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0052_alter_breaking_breaking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_quantity',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 7, 11, 16, 39, 676525, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
