# Generated by Django 4.2.7 on 2024-01-07 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0057_alter_breaking_breaking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 7, 11, 33, 45, 620906, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.DeleteModel(
            name='BreakingMaterial',
        ),
    ]
