# Generated by Django 4.2.7 on 2024-01-08 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0060_alter_breaking_breaking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breaking',
            name='breaking_material_volume',
        ),
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 8, 11, 11, 48, 652532, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
