# Generated by Django 4.2.7 on 2024-01-08 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0062_alter_breaking_breaking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 8, 11, 18, 8, 775727, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='breaking',
            name='breaking_material',
            field=models.ManyToManyField(blank=True, null=True, to='DGKP.material', verbose_name='Материалы'),
        ),
    ]
