# Generated by Django 4.2.7 on 2024-01-08 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0064_alter_breaking_breaking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='material_quantity',
        ),
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 8, 12, 34, 27, 776784, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
