# Generated by Django 4.2.7 on 2024-01-08 12:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0066_alter_breaking_breaking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 8, 12, 37, 28, 876424, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='BreakingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Количество')),
                ('breaking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DGKP.breaking', verbose_name='Заявка')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DGKP.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Материал заявки',
                'verbose_name_plural': 'Материалы заявки',
            },
        ),
    ]
