# Generated by Django 4.2.7 on 2024-01-08 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0067_alter_breaking_breaking_date_breakingmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 8, 12, 55, 0, 801686, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.DeleteModel(
            name='BreakingMaterial',
        ),
    ]
