# Generated by Django 4.2.7 on 2024-01-09 09:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0068_alter_breaking_breaking_date_delete_breakingmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 9, 9, 27, 34, 113748, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='BreakingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('breaking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DGKP.breaking')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DGKP.material')),
            ],
        ),
    ]
