# Generated by Django 4.2.7 on 2024-02-08 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0074_alter_breaking_breaking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 8, 10, 6, 34, 832792, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
