# Generated by Django 4.2.7 on 2024-02-17 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0075_alter_breaking_breaking_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breakingmaterial',
            options={'verbose_name': 'Привязанный материал', 'verbose_name_plural': 'Привязанные материалы'},
        ),
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 17, 6, 56, 59, 132393, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
