# Generated by Django 4.2.7 on 2024-02-17 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0076_alter_breakingmaterial_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 17, 6, 58, 52, 612262, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
