# Generated by Django 4.2.7 on 2024-02-17 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0078_alter_breaking_breaking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 17, 7, 0, 43, 27570, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
