# Generated by Django 4.2.7 on 2024-02-21 09:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('DGKP', '0080_breaking_breaking_email_alter_breaking_breaking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 21, 9, 41, 4, 398898, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staff_category',
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Категория'),
        ),
    ]
