# Generated by Django 4.2.7 on 2024-03-06 10:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0088_alter_breaking_breaking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 6, 10, 27, 6, 726171, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='breaking',
            name='breaking_full_name',
            field=models.CharField(max_length=70, validators=[django.core.validators.RegexValidator('[А-ЯЁёA-Z][а-яёa-z]{2,25}\\s[А-ЯЁёA-Z][а-яёa-z]{2,25}\\s[А-ЯЁёA-Z][А-Яа-яЁёA-Za-z]{2,25}\\s?')], verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='breaking',
            name='breaking_room',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(101), django.core.validators.MaxValueValidator(500)], verbose_name='Кабинет'),
        ),
    ]
