# Generated by Django 4.2.7 on 2024-03-09 08:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0089_alter_breaking_breaking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 8, 23, 49, 336621, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='breakingmaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Количество'),
        ),
    ]
