# Generated by Django 4.2.7 on 2024-03-10 17:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0090_alter_breaking_breaking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 10, 17, 58, 36, 531017, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='breaking',
            name='breaking_worker_fullname',
            field=models.ForeignKey(blank=True, default='Нет', null=True, on_delete=django.db.models.deletion.SET_NULL, to='DGKP.staff', verbose_name='Ответсвенный'),
        ),
    ]
