# Generated by Django 4.2.7 on 2024-03-10 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0092_alter_breaking_breaking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 10, 20, 23, 27, 616362, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
