# Generated by Django 4.2.7 on 2024-03-11 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DGKP', '0094_alter_breaking_breaking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking',
            name='breaking_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 11, 17, 6, 2, 246948, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
